const { defineConfig } = require("cypress");

module.exports = defineConfig({
    chromeWebSecurity: false,
    'env': {
      'codeToken': 'code',
      'password': 'password',
    },
    video: true, 
    videoCompression: 32,
    trashAssetsBeforeRuns: false,
    baseUrl: 'https://www.tutorialspoint.com/html/html_iframes.htm#',
    specPattern: "cypress/integration/*.feature",
    blockHosts: [
      "*hsappstatic.net",
      "*hubspot.com",
      "*hs-banner.com",
      "*usemessages.com",
      "*newrelic.com",
      "*nr-data.net",
      "*datadoghq.com",
      "*vidoomy.com",
      "*googlesyndication.com",
      "*servenobid.com",
      "*amazon-adsystem.com",
      "*sonobi.com",
      "*e-planning.net",
      "*casalemedia.com",
      "*rubiconproject.com",
      "*doubleclick.net",
      "*smartadserver.com",
      "*smilewanted.com",
      "*lijit.com",
      "*bidswitch.net",
      "*onetag-sys.com",
      "*3lift.com",
      "*openx.net",
      "*criteo.com",
      "*shop.pe",
      "*adsrvr.org",
      "*teads.tv",
      "*adnxs.com",
      "*pubmatic.com",
      "*jsdelivr.net",
      "*yellowblue.io",
      "*criteo.net",
      "*a-mo.net",
      "*media.net",
      "*nextmillmedia.com",
      "*adnxs.com",
      "*adpushup.com",
      "*google.com",
      "*rlcdn.com",
      "*googletagmanager.com",
      "*cloudfront.net"
      ]
    },);